services:
  openrouter-bot:
    build:
      context: ./
    container_name: bot
    env_file:
      - .env
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - openrouter_tg_bot_data:/data
      - ./model_pricing.json:/data/model_pricing.json:ro

volumes:
  openrouter_tg_bot_data: